name: Unzip File

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Unzip the File
      run: |
        sudo apt update
        sudo apt install unzip
        unzip file.zip -d ./unzipped_folder
